Repository norbit8/MoodleBooster, pull requests merged in 2021-06, with the labels that each got.

#69 Add saturation to enhance page (#64)
  content_scripts/storageLoader.js
  popup/enahnceMenu.html
  popup/popup.js
Labels: Feature

#91 dashboard module with simple api to add html content to it
  content_scripts/dashboard.js
  manifest.json
Labels: Feature

#88 [FEAT] Added chrome support (#68)
  manifest.json
  package.json
  popup/enahnceMenu.html
  popup/index.html
  popup/popup.js
  webextension-polyfill/README.md
  webextension-polyfill/dist/browser-polyfill.js
  webextension-polyfill/dist/browser-polyfill.js.map
  webextension-polyfill/dist/browser-polyfill.min.js
  webextension-polyfill/dist/browser-polyfill.min.js.map
  webextension-polyfill/package.json
Labels: Feature

#112 IdanS refactor - MERGE FIRST
  content_scripts/courseRemover.js
  content_scripts/storageLoader.js
  popup/popup.js
Labels: High Priority

#110 Line spacing and Filters bug fix (#65, #70)
  content_scripts/storageLoader.js
  popup/enahnceMenu.html
  popup/popup.js
Labels: Feature, bug
